### ISSUE TITLE
Related developments

### ISSUE THREAD

**Issue by triska** [datavetaren/prologcoin#3]
I would like to collect a few links that I hope are interesting for you.

First, there Mark Thom is also working on a new Prolog implementation, I highly recommend the vision he has outlined (please also see the filed&nbsp;issues, which contain pointers to further literature that may be relevant):

**https://github.com/mthom/rusty-wam**

Second, a Microsoft engineer has recently highlighted several design deficiencies in Solidity:

https://news.ycombinator.com/item?id=14810008

When asked for potential alternatives, the Microsoft engineer himself pointed to Prolog as a suitable candidate language:

https://news.ycombinator.com/item?id=14809743

If it is OK for you, I will post developments I come across to this issue, if I think they could be interesting for&nbsp;you.

**Comment by datavetaren** [comment]
Let me explain my rationale of using Prolog in the first place. There are multiple reasons for this, and the declarative aspect is just one aspect out of many.

The intents of implementing Prolog and use it as a generic platform for cryptocurrencies are:

1) By using an _existing_ language we'll get _existing_ source code examples, so I can run my interpreter w.r.t. other interpreters to ensure that the implementation is correct, i.e. it's easier to test and be confident that the behavior is correct. I would say this is a major problem with Solidity; it's a new language with no existing tools, which makes it very hard to compare w.r.t. a reference implementation.

2) Once the implementation is done, the consensus rules are sealed and whatever "bugs" there'll be will also be part of consensus, i.e. there no way to easily "fix" bugs. "bugs" will just become part of the consensus rules. I.e. the implementation _is_ the specification, whether you like it or not. (I'm extremely opposed to hard forks. That's not going to happen in Prologcoin.) This is why I'll be doing heavy testing (on big Prolog programs) and collect coverage to ensure that the implementation is correct (or as correct it can be.)

3) I'm creating my own Prolog-implementation precisely of reason (2). Once the implementation is done, we cannot enhance it without breaking the consensus rules. And this must never happen. This is the reason why I chose not to take an existing Prolog implementation and "do some stuff" with it.

4) The cost function (to run a Prolog program) will also be part of the consensus rules. This makes the declarative aspect even more complicated. If we add CLP to this, then the way the CLP solver is implemented will highly affect its running cost. So if CLP is added, then again we cannot go back and change it (to enhance it) without breaking the consensus rules. Implementing CLP will be a very tricky thing to do, so what I'll do is to keep the door open so it can be added via a _soft_ fork. (I'm going to avoid hard forks at all costs.)

5) Cryptocurrencies have the "reorganization problem". Backtracking makes it easy to unwind (and go back in time.) It's extremely elegant to map the solution of reorganization to Prolog backtracking.

6) A cryptocurrency needs to _validate_ consensus rules. This means that a cryptocurrency is all about validation, and predicates are perfect candidates for specifying what is true (and partition from what is untrue.)

7) UTXOs can be mapped to logic variables. By binding a variable you spend the funds. Mimblewimble is a UTXO model and we'll be using Pedersen commits as predicates. Mimblewimble is an absolute must to implement cryptocurrencies. It's the only known blockchain technology that can scale (without losing full validation.)

8) (Herbrand) Terms are perfect data structure for cryptocurrencies. They can be extended (by the use of logic variables) and they have a very efficient and compact representation. Instead of having a plain memory access model (Ethereum VM) we have a nice compact portable representation for data (to represent state.)

I don't know if Prologcoin is going to work. I'm implementing it to find out whether I can make it work. This is by no guarantee a success. But I do know I have to implement _everything_ to ensure that consensus rules are consistent.

**Comment by jacobfriedman** [comment]
I'm working in integrating Prolog with LibP2P, on the SWIPL WASM, and have gotten the Paxos library up and running. I'm now looking to make the two function together. IMO, the ISO Prolog should be the de facto prolog used for this purpose - even down to building the WASM. Building another prolog doesn't make sense. You have Scryer, GProlog, even SWI... so why are people going to want to learn another PL? 

Let's talk about catering to a community / institutions and how far we can take this by working together... would you like to have a meeting on discord or google meet to discuss a bit further? We're almost at the exact same point in our projects.

**Comment by datavetaren** [comment]
I'm sorry. I'm not interested in this. It seems that you don't understand _why_ a specific implementation is important and why the representation itself is important and why it cannot be changed once it is sealed. I repeat my points:

1) Consensus means that you cannot change things.
2) Implementation itself is part of consensus (the merkle tries that encodes the state of everything means that we cannot even change the implementation)
3) Once it is sealed we cannot even change the implementation.
4) This is true for any system that will not use hard forks - which is exactly the intent with Prologcoin.

**Comment by jacobfriedman** [comment]
1. Consensus means you reach a consensus, and that you CAN change things **as long as there's consensus**. 
2. Building on point 1: Implementation can also change, as long as there's consensus.
3. See point 2.
4. Now you're imparting your own rules on your network, great! Are they your own? Do all your collaborators consent?

Prolog is a community - and a very old one at that. Who have you discussed this idea with? I'm simply wondering... because, for the same reason there isn't a Javascriptcoin, I find it hard to understand why there should be a Prologcoin. 

Perhaps a logic-driven network in the same design of Prolog? Yes, that makes sense. But... the language shouldn't really matter, in that case - merely the protocol. If you're interested in creating something new, that's fantastic. If you're involving other people in the community rather than sealing off your design (which may never change)... I'm not so sure it's fantastic.

As my friend also said - just watch out for bugs.

**Comment by datavetaren** [comment]
Consensus means that you cannot introduce backward incompatibilities. Bitcoin never hard forks. A cryptocurrency should never hard fork. Period. Coins that do that are bad coins. Good cryptocurrencies are based on soft forks, so implementation cannot change and introduce backward incompatibilities. This is what "trust minimization" is all about. And yes, I'm defining it. Like Satoshi Nakamoto defined bitcoin. It's very hard to change bitcoin, because it should be very hard to change it. Same for Prologcoin.

And yes, we cannot have bugs. If there are bugs, they'll be part of consensus too. Unfortunately. I think that part is the most challenging.

But I'll put a lot of effort in making Prolog as much ISO compliant as possible. The consensus part of the system doesn't need to support the full Prolog language, but I want to support a relatively large subset of the language. For the non-consensus part we can make changes, but it'll be awkward if the discrepancy becomes too big between the global interpreter (consensus) and the local interpreters.

>But... the language shouldn't really matter, in that case - merely the >protocol.

The language and the environment IS the protocol.
For every node of the network, execution of the same code should result in the same state. How you encode that state is going to be highly implementation dependent. The merkle root hash of that state is what is encoded in the blocks that is then guarded with proof-of-work. And you'll not be able to easily change that. And that's the whole idea.
